# Master Camera app website

name = "mastercamera-web"
compatibility_date = "2024-12-04"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "5a16641676e84251bc640f0cc1a3493d"

[[d1_databases]]
binding = "DB"
database_name = "mastercamera-waitlist"
database_id = "caf3c2c6-3377-4166-a113-31cdf9e95bc5"
